spring:
  application:
    name: lovable
    description: This is scaled application for creating custom projects using ai

  datasource:
    url:  jdbc:postgresql://localhost:5432/lovable
    username: postgres
    password: surajnarale
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ai-client
server:
  port: 8081

keycloak:
  realm: ai-client
  auth-server-url: http://localhost:8080
  client-id: admin-cli-spring-boot
  admin-cli-secret: vh3u18F9mO62XIrKoAGxEBTxfNSmJWKI

logging:
  level:
    org:
      springframework:
        security: Trace
    io.suraj.projects.lovable: info